{{- if and (.Values.server.tls.enable) (not .Values.server.tls.existingSecret)  }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "tf-mirror.fullname" . }}-tls
  labels:
    {{- include "tf-mirror.labels" . | nindent 4 }}
data:
  tls.crt: {{ .Values.server.tls.crt | b64enc }}
  tls.key: {{ .Values.server.tls.key | b64enc }}
{{- end }}
